spring:
  application:
    name: pagination
  datasource:
    url: jdbc:mysql://localhost:3306/pagination_thymeleaf?createDatabaseIfNotExist=true
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL8Dialect